source "https://rubygems.org"

group :default do
  gem "hashie"
  gem "json"
  gem "gems"
  gem "github_api"
  # gem "octokit", "~> 4.0"
  gem 'tf-idf-similarity', '~> 0.1.5'

  gem "git"
  gem "log4r"
  # gem "license_finder"
  gem "httparty"
  gem "nokogiri"
  gem "anemone"
  gem 'rest-client'
  # This package should install by bundler as bellow:
  # gem 'bzip2-ruby', :git => 'https://github.com/chewi/bzip2-ruby.git'
  gem "ruby-xz"
end



group :test do
  gem "rspec"
  gem 'webmock'
  gem "rubocop"
  # TODO: simplecov, generate HTML
  gem 'simplecov'
  gem 'mina-puma', :git => 'https://github.com/sandelius/mina-puma.git'
end

group :development do
  gem "rake"
end

