language: ruby

rvm:
 - "2.2"

before_install:
 - sudo apt-get install -y nodejs
 - npm install bower
 - npm install semver
 - sudo apt-get install -y golang
 - sudo apt-get install -y default-jdk
 - sudo apt-get install -y maven
 - sudo add-apt-repository -y ppa:cwchien/gradle
 - sudo apt-get update
 - sudo apt-get install gradle
# - npm install
# - bundle install

script:
 - bundle exec rake build
 - bundle exec rspec spec