language: ruby, node_js

rvm:
 - "2.2"

node_js:
 - "5"

install:
 - npm install bower
 - npm install semver
# - npm install
# - bundle install

script:
 - bundle exec rake build
 - bundle exec rspec spec