language: ruby

sudo: true

rvm:
 - "2.2"

before_install:
 - sudo apt-get install -y curl
 - sudo apt-get remove -y nodejs
 - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
 - sudo apt-get install -y nodejs
 - npm install bower
 - npm install semver
 - sudo apt-get install -y golang
 - sudo add-apt-repository -y ppa:cwchien/gradle
 - sudo apt-get update
 - sudo apt-get install gradle

script:
 - bundle exec rake build
 - bundle exec rspec spec