##
# Statistic

LICENSE_SORTED_FREQUENCY = [
    'MIT',
    'Apache2.0',
    'BSD',
    'GPL2.0',
    'RubyClause-6',
    'LGPL2.1',
    'GPL3.0',
    'MPL 2.0',
    'Python',
    'LGPL3.0',
    'PublicDomain',
    'EPL1.0',
    'LGPL2.0',
    'MPL1.1',
    'CDDL1.0',
    'OpenSSL',
    'GPL1.0',
    'PerlArtistic',
    'CDDL1.1',
    'Artistic2.0',
    'TP-Free',
    'Artistic1.0',
    'AFL2.1',
    'CPL1.0',
    'Apache1.0',
]